name: Zola CI/CD

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Zola CLI
        run: |
          curl -sSL https://github.com/getzola/zola/releases/download/v0.19.1/zola-v0.19.1-x86_64-unknown-linux-gnu.tar.gz \
          | tar -xz
          sudo mv zola /usr/local/bin/zola

      - name: Build Zola site
        run: zola build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: daniellaera
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            daniellaera/daniel-blog:latest
            daniellaera/daniel-blog:${{ github.sha }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/daniel-blog
            docker pull daniellaera/daniel-blog:latest
            docker compose down || true
            docker compose up -d
            docker image prune -f

  create-release:
    name: Create GitHub Release
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "Release v${{ github.run_number }}"
          body: |
            Automated release for commit ${{ github.sha }}

            Docker images:
            - `daniellaera/daniel-blog:latest`
            - `daniellaera/daniel-blog:${{ github.sha }}`
          draft: false
          prerelease: false